### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by monksharrru** [rM-self-serve/signature-rM#1]
Hi,
I have just tried installing signature-rM by using the command `wget https://raw.githubusercontent.com/rM-self-serve/signature-rM/master/install-signature-rm.sh && bash install-signature-rm.sh && source ~/.bashrc.` However this is what I get in return:
```
Connecting to raw.githubusercontent.com (185.199.109.133:443)
wget: note: TLS certificate validation not implemented
saving to 'install-signature-rm.sh'
install-signature-rm 100% |********************************|  1911  0:00:00 ETA
'install-signature-rm.sh' saved
signature-rM v1.0.2
This program will remove the signature from the bottom
of emails sent from the device.

This program will be installed in /home/root/.local/bin
/home/root/.local/bin will be added to the path in ~/.bashrc if necessary

Would you like to continue with installation? [y/N] y
Installing signature-rM
Connecting to github.com (140.82.121.4:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
sha256sum did not pass, error downloading signature-rM
Exiting installer and removing installed files
```

Any help would be greatly appreciated. Many thanks

**Comment by rM-self-serve** [comment]
I'll take a look in a little bit!

**Comment by rM-self-serve** [comment]
Can you try running 'bash install-signature-rm.sh' again or removing the install script and trying again? I cant seem to replicate this.

**Comment by monksharrru** [comment]
> Can you try running 'bash install-signature-rm.sh' again or removing the install script and trying again? I cant seem to replicate this.

Hi, thanks for the quick reply. If you like, I will attach a screen recording of me trying to install the script?

**Comment by monksharrru** [comment]
Hi again, here is a recording of what happens, please let me know if I'm missing something !

https://i.imgur.com/FQgFbvy.mp4

**Comment by rM-self-serve** [comment]
Thank you for the great info, It seems there is an error with 'wget' for ssl support. This is very helpful as all of my install scripts likely have this behavior as well. Eventually I recommend installing the toltec package manager as it comes with a version of wget that supports ssl and this program is included.

If you feel comfortable editing the install script you can edit line 70 to 
```
wget --no-check-certificate ...
```
 
Otherwise I will have the issue resolved within the day and will close the issue so you are notified.

**Comment by monksharrru** [comment]
Hi again, thanks so much for the quick reply.
I edited the file and uploaded it to my own webserver as I thought it would be easier to do that than try to figure out how to transfer files onto the tablet - I'm pretty new to this stuff !
So I edited the file & uploaded it (https://mycoolweb.site/install-signature-rm.sh) and then edited the command to `wget https://mycoolweb.site/install-signature-rm.sh && bash install-signature-rm.sh && source ~/.bashrc` however the result is still the same! Quite possibly I have done something wrong again but no rush and thank you so much for the quick support!

> Eventually I recommend installing the toltec package manager
I have experimented with toltec recently however the features in newer versions of the reMarkable software that toltec-supported versions don't have is kind of a dealbreaker for me unfortunately! However if/when toltec gets updated to support more recent OS versions I will more than likely install it!

Many thanks

**Comment by rM-self-serve** [comment]
Thanks for giving that a try! Sorry it didn't work, I wish I could replicate the error. This one is confusing as wget is used to fetch the install script but that does not seem to error.

You are doing great! You can actually skip the install script and download the program directly as its only one file. Here are two methods as I am not sure what may work:

## 1
```
$ cd ~/.local/bin
$ wget https://github.com/rM-self-serve/signature-rM/releases/download/v1.0.2/signature-rm
$ chmod +x signature-rm
```

## 2
Download signature-rm and place it in your webserver, then replace the url from method one with 'https://mycoolweb.site/signature-rm'

As an aside, when you run ```wget https://mycoolweb.site/install-signature-rm.sh```, you are actually downloading the install file onto the device which would be considered a file transfer.

**Comment by rM-self-serve** [comment]
Would you mind sharing what software version you are running and if you have the rm1 or rm2? I have isolated the issue which was also found here here https://github.com/sabotage-linux/sabotage/issues/252. I may have to host the program on a different website 🙃.

**Comment by monksharrru** [comment]
I believe it's the latest version - 3.9.3.1986 on the rM2 :)

**Comment by monksharrru** [comment]
Hi again, I tried both your methods and unfortunately I don't believe either of them worked:

**Method 1:**
```
root@reMarkable:~# cd ~/.local/bin
root@reMarkable:~/.local/bin# wget https://github.com/rM-self-serve/signature-rM/releases/download/v1.0.2/signature-rm
Connecting to github.com (140.82.121.4:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
```
**Method 2:**
```
root@reMarkable:~/.local/bin# wget https://mycoolweb.site/signature-rm
Connecting to mycoolweb.site (107.6.161.162:443)
wget: note: TLS certificate validation not implemented
saving to 'signature-rm'
signature-rm         100% |********************************|  1458  0:00:00 ETA
'signature-rm' saved
root@reMarkable:~/.local/bin# chmod +x signature-rm
```
**Applying the program:**
```
root@reMarkable:~/.local/bin# signature-rm apply
/home/root/.local/bin/signature-rm: line 1: syntax error near unexpected token `newline'
/home/root/.local/bin/signature-rm: line 1: `<!doctype html>'
```
and unfortunately, the email still has the signature applied 😞

**Comment by rM-self-serve** [comment]
It looks like you may not have downloaded the program with Method 2. I believe you may have downloaded an html file instead. 

I have found a method to fix the installation script, I will try to have it published soon.

**Comment by monksharrru** [comment]
Ooooohhhhhh okay thank you!!

**Comment by rM-self-serve** [comment]
I believe 2e256e55c2316f76064e1c6f814bf58500470248 should fix the issue with the install script! I would appreciate you letting me know if it does. Thanks for all the help.

**Comment by monksharrru** [comment]
Hi again, I just tried using the same command to install `wget https://raw.githubusercontent.com/rM-self-serve/signature-rM/master/install-signature-rm.sh && bash install-signature-rm.sh && source ~/.bashrc` and I got this instead:

```
root@reMarkable:~# wget https://raw.githubusercontent.com/rM-self-serve/signature-rM/master/install-signature-rm.sh && bash install-signature-rm.sh && source ~/.bashrc
Connecting to raw.githubusercontent.com (185.199.109.133:443)
wget: note: TLS certificate validation not implemented
saving to 'install-signature-rm.sh'
install-signature-rm 100% |********************************|  2736  0:00:00 ETA
'install-signature-rm.sh' saved
signature-rM v1.0.2
This program will remove the signature from the bottom
of emails sent from the device.

This program will be installed in /home/root/.local/bin
/home/root/.local/bin will be added to the path in ~/.bashrc if necessary

Would you like to continue with installation? [y/N] y
Installing signature-rM
Fetching secure wget
--2024-01-02 10:01:44--  https://github.com/rM-self-serve/signature-rM/releases/download/v1.0.2/signature-rm
Resolving github.com... install-signature-rm.sh: line 94:   848 Segmentation fault      "$wget_path" "https://github.com/rM-self-serve/${gh_pkgname}/releases/download/${release}/${pkgname}" -O "$binfile"
sha256sum did not pass, error downloading signature-rM
Exiting installer and removing installed files
Would you like to remove installation script? [y/N] y
Exiting installer and removing script
```

**Comment by rM-self-serve** [comment]
Ah shoot 😅 I have one more thing for you to try before I run this up the ladder.
Make sure to remove the old install-signature-rm.sh first.
```
wget https://raw.githubusercontent.com/rM-self-serve/signature-rM/testing/install-signature-rm.sh
bash install-signature-rm.sh
```

**Comment by monksharrru** [comment]
Amazing! It worked. Thank you so much for being so helpful & patient with me 😄

**Comment by rM-self-serve** [comment]
Thank you! I will be updating my 5 repositories thanks to you.
